### PR TITLE
Issue-98: Redesign Movielist Page

### LINKED ISSUE #98: Redesign Movie List Page to Add Components from Extended Movie Table
After we start storing an extended movie table as per PR #97, we will need to add frontend display of this information. The current use of a table for display of movies does not work well with mobile and will not work well with the new extended data set (i.e. movie poster).

We will need to redesign this page to something closer to the movie cards used in the movie search (i.e. an extended version of this).

### PR DESCRIPTION
**Pull request by Thinbishop**
## Issue

Closes #98 

## Type of Change

- [ ] **Bugfix**: Change which fixes an issue
- [x] **New Feature**: Change which adds functionality
- [ ] **Documentation Update**: Change which improves documentation
- [x] **UI**: Change which improves UI

## Description

This PR implements a refactoring and improvement to the movelist page, which was previously displayed as a table to make data entry simple before TMDB was integrated. The page now contains a responsive grid of movie cards, which in addition to previous display data also contain the movie poster, imdb link, and user rating (from TMDB). Additionally, the movielist name can now be edited.

Pagination has been used to ensure there can be space for comments at the bottom of this page.

TextField autoFocus has been implemented on movie search, list creation, and list sharing.

Movielist names are now displayed on share/delete dialogs instead of list id.

## Testing the PR

Create a movie list and add/delete several movies to test pagination and add/save functionality. Test changing the title (save list afterwards).

## Checklist

- [x] **Quality**: This PR builds and passes the respective npm run test and works locally
- [ ] **Tests**: This PR includes thorough tests
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not (if applicable)
- [ ] **Documentation**: This PR includes updated/added documentation to user exposed functionality or configuration variables are added/changed or an explanation of why it does not(if applicable)

### CODE REVIEW

**Review by pyvelkov — CHANGES_REQUESTED** [review]
First off AMAZING work Jon.
I just have some small requests.

1. Can you change the background for the description on hover when adding a movie to the list. with the current theme the black background on the popup kind of gets lost.
image

2. I believe we talked about it this issue but just to confirm. Is the overlapping of the title/description/icons an issue because of the sidebar? (see image below)
image

3. Can you make the IMDB icon open a new tab instead of using the current tab? We don't want users having to go back and and forth, especially if they have not saved their list and click on the icon they will lose all their progress.

4. I cant seem to save a movie to the list neither locally nor on vercel. Can you please investigate this.
image

5. I found a small bug when a movie does not have a description/year the card is a bit smaller than the rest (see reference image below). The fix can potentially be adding a minHeight property to the card.
image

6. It seems the save button only triggers to enabled if I change the title of the list.

7. It looks like some movies are not found on IMDB. This creates several issues when saving to db and some issues that can arise on frontend. 
Frontend: Since the movie is not on imdb it will not have a link for the imdb icon. Maybe disable the icon for such movies.
DB: When I tried to save this list (after changing title) it gave me this error on the backend.
image
@chrispinkney can this be changed in the API? imdb_id is not nullable so it must have a value. instead of injecting garbage state into our db "ex: none" can we instead make the field (and others) to be nullable?

**Comment by chrispinkney** [comment]
Looks like  I can make everything nullable except genre: 
26 - 12h14m59s - ●_schema prisma_-_cinesync_-_Visual_Studio_Code

**Comment by Thinbishop** [comment]
> Looks like I can make everything nullable except genre: 

It may be better just to save the strings as blank and we can check them on the front end. Rather than having to check for null every time we access any of the data.

**Comment by chrispinkney** [comment]
I don't think you'd have to check, if it's null there just won't be anything to render right? it'll just be empty. dunno.

**Comment by Thinbishop** [comment]
> I don't think you'd have to check, if it's null there just won't be anything to render right? it'll just be empty. dunno.

Typescript is a bit wonky and won't let us use variables that show up as null. It's easier to keep it one type and check it if needed or just display an empty string

**Comment by Thinbishop** [comment]
> 1. Can you change the background for the description on hover when adding a movie to the list. with the current theme the black background on the popup kind of gets lost.

We can address this in #114 if needed. The black gives a good contrast for the text, and imo we don't need to see the tooltip background, just the text, but we can change it to something a bit lighter that still has good contrast.

> 2. I believe we talked about it this issue but just to confirm. Is the overlapping of the title/description/icons an issue because of the sidebar? (see image below)

Yes, I've been testing without the sidebar shown. As soon as the sidebar is removed in #54, we should no longer see these overlaps

> 3. Can you make the IMDB icon open a new tab instead of using the current tab? We don't want users having to go back and and forth, especially if they have not saved their list and click on the icon they will lose all their progress.

So for this, I've been testing by opening in new tab (pressing middle mouse button), I was looking into prompting the user before navigating away from the page to prevent lost changes, but it was a bit complex using the next singleton router.

Either way, I've changed it to always open in a new tab.

> 4. I cant seem to save a movie to the list neither locally nor on vercel. Can you please investigate this.

Yeah there was an issue with the context update overwriting state. I've moved the `listEdited` state to the context so it can be correctly provided to several components.

> 5. I found a small bug when a movie does not have a description/year the card is a bit smaller than the rest (see reference image below). The fix can potentially be adding a minHeight property to the card.

I've added a miHeight property that should scale responsively to the grid sizes. The code is a bit janky/verbose, but it works well for now.

> 6. It seems the save button only triggers to enabled if I change the title of the list.

See point 4 above - refactoring `listEdited`

> 7. It looks like some movies are not found on IMDB. This creates several issues when saving to db and some issues that can arise on frontend.
>    Frontend: Since the movie is not on imdb it will not have a link for the imdb icon. Maybe disable the icon for such movies.
>    DB: When I tried to save this list (after changing title) it gave me this error on the backend.
>    @chrispinkney can this be changed in the API? imdb_id is not nullable so it must have a value. instead of injecting garbage state into our db "ex: none" can we instead make the field (and others) to be nullable?

For now, I've checked if the movie coming from TMDB has either a null `imdb_id` or `poster_url` and rather set them to an empty string, this can be a workaround for the backend error we were receiving until we decide on a solution. In the frontend, the IMDB logo will now show as disabled (grey with no hover effect) with a tooltip indicating the imdb link is unavailable.

**Review by pyvelkov — APPROVED** [review]
Nice work. Tested everything I can think of. Great touch with the tooltip for the IMDB link. Everything saves properly in the DB. 
I don't think we need to touch the backend in this case. @chrispinkney your call.

**Pull request merged**
